### ISSUE TITLE
Can not use nuxt-i18n at all

### ISSUE THREAD

**Issue by begueradj** [nuxt-community/nuxt-i18n#137]
### Version

[v5.4.2](https://github.com/nuxt-i18n/releases/tag/v5.4.2)

### Reproduction link

[https://github.com/begueradj/nuxti18nerror](https://github.com/begueradj/nuxti18nerror)

### Steps to reproduce

1. Either clone my project and follow the README file instructions
2. Or create the a Nuxt.js project: `yarn create nuxt-app my-project`, then install the plugin: `yarn add nuxt-i18n` , then add it to the configuration file `nuxt.config.js`  as the official documentation says:  `modules: [  ['nuxt-i18n', {    // Options   }] ]`

### What is expected ?

I expect to launch the server without errors when I run `yarn run dev`. As simple as that.

### What is actually happening?

When I run `yarn run dev` I am getting this error message:

 INFO  Building project

✖ fatal /home/begueradj/nuxti18nerror/node_modules/nuxt-i18n/src/helpers/components.js:1
  Error: Cannot find module 'acorn-walk'
  at Object.<anonymous> (/home/begueradj/nuxti18nerror/node_modules/nuxt-i18n/src/helpers/components.js:5:16)
  at Object.Module._extensions..js (module.js:664:10)
Nuxt Fatal Error :(
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c149">#c149</a>)</em></sub></div>

**Comment by blooddrunk** [comment]
Also got the exception after upgrading from 5.3.0 to 5.4.2

**Comment by AndrewBogdanovTSS** [comment]
I guess this issue appeared just recently. I started getting it after I've upgraded from 5.4.0 to 5.4.2

**Comment by begueradj** [comment]
For anyone facing this issue, my boss solved it by adding that package: `yarn add acorn-walk`

**Comment by lucpotage** [comment]
This issue was introduced in the latest update.
https://github.com/nuxt-community/nuxt-i18n/compare/v5.4.1...v5.4.2#diff-f23f084807cac163631b6c5e9bf66ee2

Another module is used but is not included in the package.json, thus this error messsage. Thanks @begueradj  for the workaround.

**Comment by lucpotage** [comment]
Just added a pull request: https://github.com/nuxt-community/nuxt-i18n/pull/138

**Comment by begueradj** [comment]
@lucpotage I just noticed when I run `yarn add acorn-walk` to fix the issue described above,  and I launch the server, I land always  on a 404 HTTP error even if I have */pages/index.vue* file. Any hints?

**Comment by paulgv** [comment]
Sorry about that! Fix is released under v5.4.3, thanks for the PR @lucpotage
