### PR TITLE
fix: remove explicit dependency on vue-template-compiler (fixes #297)

### LINKED ISSUE #297: Implicit dependency on `vue-template-compiler`
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://github.com/nuxt/now-builder/issues/42](https://github.com/nuxt/now-builder/issues/42)

### Steps to reproduce

-

### What is expected ?

-

### What is actually happening?

-

### Additional comments?

This module has an implicit dependency on `vue-template-compiler` [here](https://github.com/nuxt-community/nuxt-i18n/blob/master/src/helpers/components.js#L6). All direct dependencies like this should be specified in `dependencies` section of package.json.  When using `nuxt-start` (a serverless) build of nuxt, this dependency is not available.

It is also better to only require build related deps on `build:before` nuxt hook to prevent additional overhead when running in production mode.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c237">#c237</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by rchl**
We can't have explicit dependency as that package requires its and vue's
versions to match exactly and we can't ensure that. Remove it and just
make sure that this dependency is only used on building nuxt app (done
before already, just added more explanation in comments).

### CODE REVIEW

**Comment by dzcpy** [comment]
Can we add vue-template-compiler to peer dependency?
https://docs.npmjs.com/files/package.json#peerdependencies
I can't get it work with freshly installed nuxt 2.10 and nuxt-i18n 6.4.1
```
i Preparing project for development                                                                                                                                                                                          03:36:21
i Initial build may take a while                                                                                                                                                                                             03:36:21
√ Builder initialized                                                                                                                                                                                                        03:36:21
(node:7152) UnhandledPromiseRejectionWarning: C:\Users\Administrator\Desktop\node_modules\nuxt-i18n\src\helpers\components.js:1
Error: Cannot find module 'vue-template-compiler'
Require stack:
- C:\Users\Administrator\Desktop\node_modules\nuxt-i18n\src\helpers\components.js
- C:\Users\Administrator\Desktop\node_modules\nuxt-i18n\src\helpers\routes.js
- C:\Users\Administrator\Desktop\node_modules\nuxt-i18n\src\index.js
- C:\Users\Administrator\Desktop\nuxt-test\node_modules\@nuxt\core\dist\core.js
- C:\Users\Administrator\Desktop\nuxt-test\node_modules\nuxt\dist\nuxt.js
- C:\Users\Administrator\Desktop\nuxt-test\server\index.js
    at Object.<anonymous> (C:\Users\Administrator\Desktop\node_modules\nuxt-i18n\src\helpers\components.js:8:18)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
(node:7152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[nodemon] clean exit - waiting for changes before restart
```
